apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: federatorai-operator-servicesmutation
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: federatorai-operator
      namespace: federatorai
      path: /mutate-federatorai-containers-ai-v1alpha1-alamedaservice
  failurePolicy: Fail
  name: alamedaservicemutate.federatorai.containers.ai
  rules:
  - apiGroups:
    - federatorai.containers.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alamedaservices