apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: federatorai-operator-servicesvalidation
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: federatorai-operator
      namespace: federatorai
      path: /validate-federatorai-containers-ai-v1alpha1-alamedaservice
  failurePolicy: Fail
  name: alamedaservicevalidate.federatorai.containers.ai
  rules:
  - apiGroups:
    - federatorai.containers.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alamedaservices
  sideEffects: None